name: Robot Framework Browser Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        browser: [chrome]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Robot Framework and Browser library
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init
          pip install robotframework-metrics

      - name: Install Chrome Driver
        run: |
          choco install chromedriver

      - name: Run Robot Framework tests
        run: |
          robot --outputdir output tests/

      - name: Generate metrics report
        run: |
          cd output
          robotmetrics -M metrics.html

      - name: Publish Robot Framework results
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-results
          path: output/
